skip_docs

before_all do |lane, options|
  xcversion(version: '~> 12.5')
end

desc 'Bootstrap'
lane :bootstrap do
  decrypt_repo
  download_certs
end

desc 'Sync Provisioning Profiles'
lane :download_certs do
  sync_code_signing(readonly: true, type: 'development')
  sync_code_signing(readonly: true, type: 'appstore')
end

desc 'Run All Tests'
lane :test do
  run_tests(
    scheme: 'All',
    device: 'iPhone 8',
    configuration: 'Debug',
  )
end

desc 'Build For Release'
lane :build_for_release do
  build_app(
    scheme: 'All',
    configuration: 'Release',
    skip_package_ipa: true,
  )
end

desc 'CI | Pull Request'
lane :ci_pull_request do
  test
  build_for_release
end
