#!/bin/bash

if ! which git-crypt > /dev/null; then
    brew install git-crypt
fi

PRIVATE_KEY=$1
git-crypt unlock $PRIVATE_KEY

SCRIPT_DIR=$(dirname $0)
$SCRIPT_DIR/build_phase_generate_asset_symbols
$SCRIPT_DIR/build_phase_generate_enum_properties
