#!/bin/bash

set -e

if ! which git-crypt > /dev/null; then
    HOMEBREW_NO_AUTO_UPDATE=1 \
    brew install git-crypt
fi

PRIVATE_KEY=$1
git-crypt unlock $PRIVATE_KEY

SCRIPT_DIR=$(dirname $0)
SSH_PATH=$2
GIT_URL=$3
$SCRIPT_DIR/fetch_certificates $SSH_PATH $GIT_URL
