#!/bin/bash

if ! which sourcery > /dev/null; then
    HOMEBREW_NO_AUTO_UPDATE=1 \
    brew install sourcery
fi

sourcery \
    --sources Rythmico/RequestLessonPlan/LessonPlanRequestFlow/RequestLessonPlanContext.swift \
    --templates Rythmico/Supporting\ Files/EnumProperties.stencil \
    --output Rythmico/Supporting\ Files
