#!/usr/bin/env bash

set -e

set -o pipefail && \
    xcodebuild \
        -project Rythmico.xcodeproj \
        -scheme All \
        -destination generic/platform=iOS \
        -configuration Release \
        clean build | xcbeautify
