#!/usr/bin/env bash

swiftgen run xcassets \
    "$SRCROOT/$TARGET_NAME/Supporting Files/Assets.xcassets" \
    --templateName swift4 \
    --output "$SRCROOT/$TARGET_NAME/Supporting Files/Assets.generated.swift"
