#!/bin/bash

if ! which sourcery > /dev/null; then
    HOMEBREW_NO_AUTO_UPDATE=1 \
    brew install sourcery
fi

sourcery \
    --sources Services \
    --sources UI \
    --sources Rythmico \
    --exclude-sources Services/ActivityCoordinator.swift \
    --exclude-sources Rythmico/Root/RootView.swift \
    --templates Rythmico/Supporting\ Files/EnumProperties.stencil \
    --output Rythmico/Supporting\ Files
