#!/usr/bin/env bash

set -e

xcodebuild \
    -project Rythmico.xcodeproj \
    -scheme All \
    -destination generic/platform=iOS \
    -configuration Release \
    clean build | xcpretty -s -c

exit ${PIPESTATUS[0]}
