#!/bin/bash

# Run this after fetch_certificates_apns
# if APNS certs need to be renewed too.

GIT_URL="git@github.com:rythmico/ios-certs.git"
TEAM_ID="72N659HYBR"
APP_IDS="com.rythmico.student,com.rythmico.tutor"

fastlane match nuke development \
  --git_url "$GIT_URL" \
  --team-id "$TEAM_ID"
fastlane match development \
  --git_url "$GIT_URL" \
  --team-id "$TEAM_ID" \
  --app_identifier "$APP_IDS"

fastlane match nuke distribution \
  --git_url "$GIT_URL" \
  --team-id "$TEAM_ID"
fastlane match appstore \
  --git_url "$GIT_URL" \
  --team-id "$TEAM_ID" \
  --app_identifier "$APP_IDS"