#!/bin/bash

# Remove existing APNS certs before running this.
# Run this first before fetch_certificates so the
# APNS certs are bundled into the distribution profiles.

TEAM_ID="72N659HYBR"
APP_ID_STUDENT="com.rythmico.student"
APP_ID_TUTOR="com.rythmico.tutor"
OUTPUT_PATH="/tmp"

fastlane pem --development \
  --team-id "$TEAM_ID" \
  --app_identifier "$APP_ID_STUDENT" \
  --output_path "$OUTPUT_PATH"
fastlane pem \
  --team-id "$TEAM_ID" \
  --app_identifier "$APP_ID_STUDENT" \
  --output_path "$OUTPUT_PATH"

fastlane pem --development \
  --team-id "$TEAM_ID" \
  --app_identifier "$APP_ID_TUTOR" \
  --output_path "$OUTPUT_PATH"
fastlane pem \
  --team-id "$TEAM_ID" \
  --app_identifier "$APP_ID_TUTOR" \
  --output_path "$OUTPUT_PATH"