#!/usr/bin/env bash

set -e

results_dir=$1

xcodebuild \
    -project Rythmico.xcodeproj \
    -scheme All \
    -destination 'platform=iOS Simulator,name=iPhone 8' \
    -configuration Debug \
    clean test | \
    xcpretty -s -c \
    ${results_dir:+"-r junit"} \
    ${results_dir:+"-o $results_dir/test_results"}

exit ${PIPESTATUS[0]}
