#!/usr/bin/env bash

set -e

xcodebuild \
    -project Rythmico.xcodeproj \
    -scheme All \
    -destination 'platform=iOS Simulator,name=iPhone 8' \
    -configuration Debug \
    clean test | xcpretty -sc -r junit

exit ${PIPESTATUS[0]}
