#!/usr/bin/env bash

PATH=${PATH}:/opt/homebrew/bin

swiftgen run xcassets \
    "$SRCROOT/$TARGET_NAME/Supporting Files/Assets.xcassets" \
    --templateName swift5 \
    --output "$SRCROOT/$TARGET_NAME/Supporting Files/Assets.generated.swift"
