name: CI

on: [pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    name: ${{ matrix.platform.name }}
    runs-on: macos-11
    env:
      GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'iOS 14.5', destination: "'platform=iOS Simulator,name=iPhone 8,OS=14.5'" }

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Bootstrap
        run: make bootstrap
      - name: CI
        run: bundle exec fastlane ci
